// react/src/components/TodoEditor.tsx
export default function TodoEditor() {
  return (
    <form className="flex p-4 mb-3">
      <input
        type="text"
        placeholder="Enter a new todo"
        className="flex-grow p-2 text-white focus:outline-none border-2 border-[#61dafb] rounded-l-md placeholder-white/30"
      />
      <button className="bg-[#61dafb] px-4 rounded-r-md cursor-pointer">
        Add
      </button>
    </form>
  );
}

// vue/pinia/src/components/TodoEditor.vue
<script setup>
import { useTodoStore } from '@/stores/todo'
import { ref } from 'vue'

const { addTodo } = useTodoStore()
const text = ref('')

const handleSubmit = () => {
  addTodo(text.value)
  text.value = ''
}
</script>
<template>
  <form class="flex p-4 mb-3" @submit.prevent="handleSubmit">
    <input
      v-model="text"
      type="text"
      placeholder="Enter a new todo"
      class="flex-grow p-2 focus:outline-none border-2 border-[#2c8b73] rounded-l-md"
    />
    <button class="bg-[#2c8b73] text-[#ffffff] px-4 rounded-r-md cursor-pointer">Add</button>
  </form>
</template>
<style scoped></style>
