// react/src/components/Todo.tsx
import { useEffect, useState } from 'react';
import TodoEditor from './TodoEditor';
import TodoHeader from './TodoHeader';
import TodoList from './TodoList';

export type TodoType = {
  id: number;
  text: string;
  completed: boolean;
};

export default function Todo() {
  const [todos, setTodos] = useState<TodoType[]>(() => {
    // 불러오기
    const saved = localStorage.getItem('todos');
    return saved ? JSON.parse(saved) : [];
  });

  // 저장
  useEffect(() => {
    localStorage.setItem('todos', JSON.stringify(todos));
  });

  // 할 일 등록
  const addTodo = (text: string) => {
    const newTodo: TodoType = {
      id: Date.now(),
      text,
      completed: false,
    };

    setTodos([...todos, newTodo]);
  };

  // 할 일 완료 여부 토글
  const toggleTodo = (id: number) => {
    setTodos(
      todos.map((todo) =>
        todo.id === id ? { ...todo, completed: !todo.completed } : todo
      )
    );
  };

  // 할 일 삭제
  const deleteTodo = (id: number) => {
    setTodos(todos.filter((todo) => todo.id !== id));
  };

  // 할 일 수정
  const modifyTodo = (id: number, text: string) => {
    setTodos(todos.map((todo) => (todo.id === id ? { ...todo, text } : todo)));
  };

  return (
    <>
      <TodoHeader />
      <TodoEditor addTodo={addTodo} />
      <div className='overflow-y-auto'>
        <TodoList
          todos={todos}
          toggleTodo={toggleTodo}
          deleteTodo={deleteTodo}
          modifyTodo={modifyTodo}
        />
      </div>
    </>
  );
}

// vue/composition-api/src/components/Todo.vue
<script setup>
import { onMounted, ref, watch } from 'vue'
import TodoEditor from './TodoEditor.vue'
import TodoHeader from './TodoHeader.vue'
import TodoList from './TodoList.vue'

const todos = ref([])

const addTodo = (text) => {
  todos.value.push({
    id: Date.now(),
    text,
    done: false,
  })
}

const toggleTodo = (id) => {
  todos.value = todos.value.map((todo) => (todo.id === id ? { ...todo, done: !todo.done } : todo))
}

const deleteTodo = (id) => {
  todos.value = todos.value.filter((todo) => todo.id !== id)
}

// 저장
watch(
  todos,
  (newTodos) => {
    sessionStorage.setItem('todos', JSON.stringify(newTodos))
  },
  { deep: true },
)

// 복원
onMounted(() => {
  const saved = sessionStorage.getItem('todos')
  if (saved) {
    todos.value = JSON.parse(saved)
  }
})
</script>
<template>
  <TodoHeader />
  <TodoEditor @addTodo="addTodo" />
  <div class="overflow-y-auto flex-1">
    <TodoList :todos="todos" @toggleTodo="toggleTodo" @deleteTodo="deleteTodo" />
  </div>
</template>
<style scoped></style>
