// react/src/components/TodoListItem.tsx
export default function TodoListItem() {
  return (
    <>
      <li className="flex items-center justify-between p-4">
        <div className="flex items-center">
          <input
            type="checkbox"
            className="mr-3 h-4 w-4 accent-[#61dafb] cursor-pointer"
          />
          <span className="text-white">음악 듣기</span>
        </div>
        <button className="text-red-500 cursor-pointer">Delete</button>
      </li>
    </>
  );
}

// vue/composition-api/src/components/TodoListItem.vue
<script setup>
const props = defineProps({
  todo: {
    type: Object,
  },
})

const emit = defineEmits(['toggleTodo', 'deleteTodo'])

const handleToggle = () => {
  emit('toggleTodo', props.todo.id)
}

const handleDelete = () => {
  emit('deleteTodo', props.todo.id)
}
</script>
<template>
  <li class="flex items-center justify-between p-3">
    <div class="flex items-center">
      <input
        type="checkbox"
        class="mr-3 h-4 w-4 accent-[#35495e]"
        @change="handleToggle"
        :checked="props.todo.done"
      />
      <span :class="{ 'line-through text-gray-400': props.todo.done }">{{ props.todo.text }}</span>
    </div>
    <button class="text-red-500 cursor-pointer" @click="handleDelete">Delete</button>
  </li>
</template>
<style scoped></style>
