// react/src/components/TodoEditor.tsx
export default function TodoEditor() {
  return (
    <form className="flex p-4 mb-3">
      <input
        type="text"
        placeholder="Enter a new todo"
        className="flex-grow p-2 text-white focus:outline-none border-2 border-[#61dafb] rounded-l-md placeholder-white/30"
      />
      <button className="bg-[#61dafb] px-4 rounded-r-md cursor-pointer">
        Add
      </button>
    </form>
  );
}

// vue/src/components/TodoEditor.vue
<script setup></script>
<template>
  <form class="flex p-4 mb-3">
    <input
      type="text"
      placeholder="Enter a new todo"
      class="flex-grow p-2 focus:outline-none border-2 border-[#2c8b73] rounded-l-md"
    />
    <button
      type="button"
      class="bg-[#2c8b73] text-[#ffffff] px-4 rounded-r-md cursor-pointer hover:bg-[#277d68]"
    >
      Add
    </button>
  </form>
</template>
<style scoped></style>
