// react/src/components/TodoList.tsx
import type { TodoType } from './Todo';
import TodoListItem from './TodoListItem';

interface TodoListProps {
  todos: TodoType[];
  toggleTodo: (id: number) => void;
  deleteTodo: (id: number) => void;
}

export default function TodoList({
  todos,
  toggleTodo,
  deleteTodo,
}: TodoListProps) {
  return (
    <ul className="divide-y divide-[#333]">
      {todos.map((todo) => (
        <TodoListItem
          todo={todo}
          key={todo.id}
          toggleTodo={toggleTodo}
          deleteTodo={deleteTodo}
        />
      ))}
    </ul>
  );
}

// vue/src/components/TodoList.vue
<script setup>
import { useTodoStore } from '@/stores/todo'
import TodoListItem from './TodoListItem.vue'

const todoStore = useTodoStore()
</script>
<template>
  <ul class="divide-y divide-gray-200">
    <TodoListItem v-for="todo in todoStore.todos" :key="todo.id" :todo="todo" />
  </ul>
</template>
<style scoped></style>
