// vue/options-api/src/App.vue
<script>
import Todo from './components/Todo.vue'

export default {
  name: 'App',
  components: {
    Todo,
  },
}
</script>
<template>
  <div class="flex items-center justify-center min-h-screen bg-[#faf3dd]">
    <div
      class="max-w-md w-full h-[500px] bg-[#ffffff] rounded-lg shadow-lg overflow-hidden flex flex-col"
    >
      <Todo />
    </div>
  </div>
</template>
<style scoped></style>

// react/src/App.tsx
import Todo from './components/Todo';

export default function App() {
  return (
    <div className="flex items-center justify-center min-h-screen bg-[#1e1e1e]">
      <div className="max-w-md w-full h-[500px] bg-[#1c1c1c] border border-[#333] rounded-lg shadow-lg overflow-hidden flex flex-col">
        <Todo />
      </div>
    </div>
  );
}
