// vue/src/App.vue
<script setup>
import Todo from './components/Todo.vue'
</script>
<template>
  <div class="flex items-center justify-center min-h-screen bg-[#faf3dd]">
    <div
      class="w-full max-w-md h-[580px] bg-[#ffffff] rounded-lg shadow-lg overflow-hidden flex flex-col"
    >
      <Todo />
    </div>
  </div>
</template>
<style scoped></style>

// react/src/App.tsx
import Todo from './components/Todo';

export default function App() {
  return (
    <div className="flex items-center justify-center min-h-screen bg-[#1e1e1e]">
      <div className="max-w-md w-full h-[500px] bg-[#1c1c1c] border border-[#333] rounded-lg shadow-lg overflow-hidden flex flex-col">
        <Todo />
      </div>
    </div>
  );
}
