// vue/composition-api/src/components/TodoList.vue
<script setup>
import TodoListItem from './TodoListItem.vue'

const props = defineProps({
  todos: {
    type: Array,
  },
})

const emit = defineEmits(['toggleTodo', 'deleteTodo'])

const toggleTodo = (id) => {
  emit('toggleTodo', id)
}

const deleteTodo = (id) => {
  emit('deleteTodo', id)
}
</script>
<template>
  <ul class="divide-y divide-gray-200">
    <TodoListItem
      v-for="todo in props.todos"
      :key="todo.id"
      :todo="todo"
      @toggleTodo="toggleTodo"
      @deleteTodo="deleteTodo"
    />
  </ul>
</template>
<style scoped></style>

// react/src/components/TodoList.tsx
import type { TodoType } from './Todo';
import TodoListItem from './TodoListItem';

interface TodoListProps {
  todos: TodoType[];
  toggleTodo: (id: number) => void;
  deleteTodo: (id: number) => void;
}

export default function TodoList({
  todos,
  toggleTodo,
  deleteTodo,
}: TodoListProps) {
  return (
    <ul className="divide-y divide-[#333]">
      {todos.map((todo) => (
        <TodoListItem
          todo={todo}
          key={todo.id}
          toggleTodo={toggleTodo}
          deleteTodo={deleteTodo}
        />
      ))}
    </ul>
  );
}
