// vue/src/components/TodoListItem.vue
<script setup></script>
<template>
  <li class="flex items-center justify-between p-4">
    <div class="flex items-center">
      <input type="checkbox" class="mr-4 h-4 w-4 accent-[#35495e]" />
      <span>아침 먹기</span>
    </div>
    <button type="button" class="text-red-500 cursor-pointer hover:text-red-600">Delete</button>
  </li>
</template>
<style scoped></style>

// react/src/components/TodoListItem.tsx
export default function TodoListItem() {
  return (
    <>
      <li className="flex items-center justify-between p-4">
        <div className="flex items-center">
          <input
            type="checkbox"
            className="mr-3 h-4 w-4 accent-[#61dafb] cursor-pointer"
          />
          <span className="text-white">음악 듣기</span>
        </div>
        <button className="text-red-500 cursor-pointer">Delete</button>
      </li>
    </>
  );
}
