// vue/options-api/src/components/TodoList.vue
<script>
import TodoListItem from './TodoListItem.vue'

export default {
  name: 'TodoList',
  components: {
    TodoListItem,
  },

  props: {
    todos: {
      type: Array,
    },
  },

  emits: ['toggleTodo', 'deleteTodo'],

  methods: {
    toggleTodo(id) {
      this.$emit('toggleTodo', id)
    },

    deleteTodo(id) {
      this.$emit('deleteTodo', id)
    },
  },
}
</script>
<template>
  <ul class="divide-y divide-gray-200">
    <TodoListItem
      v-for="todo in todos"
      :key="todo.id"
      :todo="todo"
      @toggleTodo="toggleTodo"
      @deleteTodo="deleteTodo"
    />
  </ul>
</template>
<style scoped></style>

// react/src/components/TodoList.tsx
import type { TodoType } from './Todo';
import TodoListItem from './TodoListItem';

interface TodoListProps {
  todos: TodoType[];
  toggleTodo: (id: number) => void;
  deleteTodo: (id: number) => void;
}

export default function TodoList({
  todos,
  toggleTodo,
  deleteTodo,
}: TodoListProps) {
  return (
    <ul className="divide-y divide-[#333]">
      {todos.map((todo) => (
        <TodoListItem
          todo={todo}
          key={todo.id}
          toggleTodo={toggleTodo}
          deleteTodo={deleteTodo}
        />
      ))}
    </ul>
  );
}
